In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,2])

In [3]:
arr1.ndim

1

In [4]:
arr1.shape

(3,)

In [5]:
arr1.size

3

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.dtype

dtype('int32')

In [8]:
arr1.itemsize

4

In [9]:
arr1.max()

2

In [13]:
arr1.sum()

5

In [11]:
arr1.min()

1

In [12]:
arr2=np.array([[1,2,4],[5,3,7],[5,3,2]])

In [13]:
arr2

array([[1, 2, 4],
       [5, 3, 7],
       [5, 3, 2]])

In [17]:
arr2=arr2.T

In [18]:
arr2

array([[1, 2, 4],
       [5, 3, 7],
       [5, 3, 2]])

In [19]:
arr2

array([[1, 2, 4],
       [5, 3, 7],
       [5, 3, 2]])

In [20]:
arr2.diagonal()

array([1, 3, 2])

In [21]:
arr2.sort(0)

In [22]:
arr2

array([[1, 2, 2],
       [5, 3, 4],
       [5, 3, 7]])

In [23]:
arr3=[[[21,1,3,2],[4,2,1,3]],[[21,1,3,2],[4,2,1,3]],[[21,1,3,2],[4,2,1,3]],[[21,1,3,2],[4,2,1,3]]]

In [24]:
arr3=np.array(arr3)

In [25]:
arr3.shape

(4, 2, 4)

In [26]:
arr=np.arange(0,10,2.5)

In [27]:
arr

array([0. , 2.5, 5. , 7.5])

In [41]:
arr=np.linspace(2,5,3)

In [42]:
arr

array([2. , 3.5, 5. ])

In [60]:
arr=np.random.random

C:\Users\Ronak\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(3, 4 + 1) instead
  """Entry point for launching an IPython kernel.


In [58]:
arr

8

In [28]:
ar1=np.eye(4)

In [29]:
ar1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
ar1.diagonal()

array([1., 1., 1., 1.])

In [32]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.random.rand(1,2)

array([[0.28251503, 0.34568184]])

In [42]:
arr1=np.random.randint(2,9,(5,6))

In [47]:
arr1=arr1.reshape(3,10)

In [51]:
arr1.argmin()

4

In [52]:
arr1

array([[3, 8, 7, 5, 2, 5, 6, 7, 8, 3],
       [7, 4, 3, 2, 3, 7, 7, 5, 3, 8],
       [5, 7, 5, 7, 6, 2, 3, 6, 4, 3]])

In [53]:
arr1.shape

(3, 10)

In [55]:
array_hey=np.arange(4,20,3)

In [56]:
array_hey

array([ 4,  7, 10, 13, 16, 19])

In [58]:
array_hey[1:]

array([ 7, 10, 13, 16, 19])

In [68]:
array_hey=array_hey.reshape(2,3)

In [72]:
array_hey[1][1]=22

In [73]:
array_hey

array([[ 4,  7, 10],
       [13, 22, 19]])